### PR TITLE
Published 0.4.0

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by eddyb** [comment]
Wait, why did you bump the version here? I see no breaking changes.

**Comment by bvssvni** [comment]
@eddyb It was probably version bumped to be on the safe side.

**Comment by eddyb** [comment]
@bvssvni I find that problematic because it means any improvements/bugfixes have to be manually backported. I'd suggest using something like [`rust-semverver`](https://github.com/rust-lang-nursery/rust-semverver) to make the decision.

**Comment by bvssvni** [comment]
@eddyb Thanks!

**Comment by eddyb** [comment]
@bvssvni Do you think you could publish the last (assuming there are no breaking changes - I couldn't find any myself) version as new patch versions under `0.1`, `0.2` and `0.3`?

**Comment by bvssvni** [comment]
@eddyb I'm going on vacation now. :)

**Comment by bvssvni** [comment]
@eddyb It's just `cargo publish`. Nothing complicated. Have to go.

**Pull request merged**
